apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnypdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnypdb-app
  template:
    metadata:
      labels:
        app: vnypdb-app
    spec:
      containers:
      - name: vnypdb-app
        image: vinaypdb/vnypdb-app:latest
        ports:
        - containerPort: 8080
